"""Export categorized, public county-resource API records for the transfer stage.

The JSONL is private transfer input: only artifact descriptors contain local
paths. API item/detail objects are generated by the same adapter as localhost.
No Supabase credentials, remote writes, crawling, or database writes occur here.
"""
from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import sys
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / '_transfer_scratch/supabase_export/county_litigation.jsonl'


def adapter_module():
    spec = importlib.util.spec_from_file_location('_local_county_litigation_adapter', ROOT / 'delivery/archive-directory/county_litigation.py')
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def excluded_reason(row, held_ids=()):
    meta = row.get('metadata') or {}
    if row.get('id') in held_ids:
        return 'Explicit publication holdback'
    if row.get('resource_kind') == 'unknown':
        return 'Uncategorized resource'
    classification = meta.get('classification') or {}
    if classification.get('status') == 'preserved_prior_negative_review' or meta.get('document_shape') == 'reviewed_non_litigation_reference':
        return 'Preserved prior non-litigation review'
    if meta.get('document_shape') in {'access_error', 'possible_filed_pleading'}:
        return 'Source content is access-error or unreviewed filed-pleading material'
    if '/media-releases/' in row.get('source_url', '') and re.search(r'\bgraduat(?:ion|e|es|ed)\b', row.get('title', ''), re.I):
        return 'Court graduation event news, not a litigation resource'
    return None


def _write_json(path, value):
    path.write_bytes((json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode('utf-8'))


def write_dataset_descriptor(output, receipt, adapter, baseline=None):
    """Facet counts describe exported rows, never excluded source records."""
    availability = Counter()
    kinds = Counter()
    index = []
    with Path(output).open(encoding='utf-8') as source:
        for line in source:
            row = json.loads(line)
            availability[row['item']['availability']] += 1
            kinds[row['category']] += 1
            index.append({'id': row['id'], 'state': row['state'], 'county_geoids': row['county_geoids'],
                          'title': row['title'], 'county': row['item'].get('county') or '',
                          'resource_type': row['category'], 'availability': row['item']['availability'],
                          'document_shape': row['item'].get('document_shape')})
    if sum(kinds.values()) != receipt['exported_rows']:
        raise ValueError('Export descriptor count differs from receipt')
    baseline = baseline or {'available': True, 'qualification': adapter.QUALIFICATION,
                            'validated_at': receipt['source_publication_validated_at']}
    listing = {k: v for k, v in baseline.items() if k not in {'items', 'total', 'page', 'limit', 'facets', 'county_geoid'}}
    listing['facets'] = {'resource_types': [{'value': kind, 'label': label, 'count': kinds[kind]}
                                           for kind, label in adapter.TYPES.items() if kinds[kind]],
                         'availability': [{'value': kind, 'label': label, 'count': availability[kind]}
                                          for kind, label in adapter.AVAILABILITY.items() if availability[kind]]}
    descriptor = {'id': 'county_litigation', 'label': 'County litigation resources', 'export_jsonl_sha256': receipt['output_sha256'],
                  'expected_records': receipt['exported_rows'], 'listing': listing, 'summary': receipt, 'filter_index': index}
    _write_json(Path(output).with_suffix('.dataset.json'), descriptor)
    return descriptor


def export(output=DEFAULT_OUTPUT, folder=None, adapter=None):
    adapter = adapter or adapter_module()
    folder = Path(folder or adapter.DATA).resolve()
    output = Path(output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    gate_path = folder / 'validation.json'
    gate_before = gate_path.read_bytes()
    snapshot = adapter.load(folder)
    if not snapshot.get('gate') or snapshot['gate'].get('ready') is not True or snapshot['gate'].get('status') != 'passed':
        raise ValueError('County publication gate is closed or artifact integrity failed')
    if gate_before != gate_path.read_bytes():
        raise ValueError('County publication changed while loading')
    held_file = folder / 'publication_holdbacks.jsonl'
    held_bytes = held_file.read_bytes() if held_file.exists() else b''
    held = [json.loads(line) for line in held_bytes.decode('utf-8-sig').splitlines() if line.strip()]
    held_ids = {row['id'] for row in held}
    exclusions = []
    counts = Counter()
    total_bytes = 0
    text_characters = 0
    temp = output.with_name(output.name + '.tmp')
    try:
        with temp.open('w', encoding='utf-8', newline='\n') as stream, patch.object(adapter, 'load', return_value=snapshot):
            first = adapter.query({'include_directories': '1', 'page': 1, 'limit': 100}, folder)
            if first.get('available') is not True or first.get('total') != len(snapshot['rows']):
                raise ValueError('Adapter listing does not match validated snapshot')
            for page in range(1, (first['total'] + 99) // 100 + 1):
                result = first if page == 1 else adapter.query({'include_directories': '1', 'page': page, 'limit': 100}, folder)
                for item in result['items']:
                    row = snapshot['rows'][item['id']]
                    reason = excluded_reason(row, held_ids)
                    if reason:
                        exclusions.append({'id': row['id'], 'title': row['title'], 'source_url': row['source_url'], 'reason': reason})
                        continue
                    detail = adapter.detail(row['id'], folder)
                    if detail is None:
                        raise ValueError('Validated resource lacks an adapter reader: ' + row['id'])
                    detail.pop('text', None)
                    artifacts = []
                    text = ''
                    for role, descriptor in row['_assets'].items():
                        captured = adapter.asset(row['id'], role, folder)
                        if captured is None:
                            raise ValueError('Resource artifact failed verification: ' + row['id'])
                        data, mime, _ = captured
                        if role == 'text':
                            text = data.decode('utf-8-sig', errors='replace')
                        url = item.get('original_url' if role == 'original' else 'text_url')
                        if not url:
                            raise ValueError('Saved artifact lacks a public API URL')
                        artifacts.append({'role': role, 'url': url, 'local_path': str(descriptor['_path'].resolve()),
                                          'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data), 'mime': mime})
                        total_bytes += len(data)
                    record = {'id': row['id'], 'dataset': 'county_litigation', 'category': row['resource_kind'],
                              'state': item.get('state'), 'county_geoids': item.get('county_geoids') or [],
                              'title': item['title'], 'source_url': item['source_url'], 'item': item, 'detail': detail,
                              'text': text, 'filters': {key: item.get(key) for key in
                                                      ('state', 'county_geoids', 'resource_type', 'availability', 'document_shape')},
                              'artifacts': artifacts}
                    stream.write(json.dumps(record, ensure_ascii=False, separators=(',', ':')) + '\n')
                    counts[row['resource_kind']] += 1
                    text_characters += len(text)
        if gate_before != gate_path.read_bytes() or any(adapter._stamp(path) != stamp for path, stamp in snapshot['watched'].items()):
            raise ValueError('County publication changed during export')
        if (held_file.read_bytes() if held_file.exists() else b'') != held_bytes:
            raise ValueError('Publication holdbacks changed during export')
        for row in held:
            if row['id'] not in snapshot['rows']:
                exclusions.append({'id': row['id'], 'title': row.get('title'), 'source_url': row.get('source_url'),
                                   'reason': row.get('reason') or 'Explicit publication holdback', 'already_absent_from_publication': True})
        output_hash = hashlib.sha256(temp.read_bytes()).hexdigest()
        exclusions_path = output.with_suffix('.excluded.jsonl')
        exclusions_temp = exclusions_path.with_name(exclusions_path.name + '.tmp')
        exclusions_temp.write_bytes((''.join(json.dumps(r, ensure_ascii=False) + '\n' for r in exclusions)).encode('utf-8'))
        temp.replace(output)
        exclusions_temp.replace(exclusions_path)
        receipt = {'status': 'passed', 'created_at': datetime.now(timezone.utc).isoformat(), 'dataset': 'county_litigation',
                   'source_rows': len(snapshot['rows']), 'exported_rows': sum(counts.values()),
                   'excluded_present_rows': len(snapshot['rows']) - sum(counts.values()),
                   'excluded_total_with_prior_holdbacks': len(exclusions), 'by_category': dict(counts),
                   'gate_sha256': hashlib.sha256(gate_before).hexdigest(), 'output_sha256': output_hash,
                   'output_bytes': output.stat().st_size, 'artifact_reference_bytes': total_bytes,
                   'full_text_characters': text_characters, 'source_publication_validated_at': snapshot['gate'].get('validated_at'),
                   'network_requests': 0, 'remote_writes': 0,
                   'local_paths_private_transfer_only': True, 'source_snapshot_unchanged': True}
        _write_json(output.with_suffix('.receipt.json'), receipt)
        write_dataset_descriptor(output, receipt, adapter, first)
        return receipt
    except Exception:
        if temp.exists():
            temp.unlink()
        raise


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--folder', type=Path)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    print(json.dumps(export(args.output, args.folder)))
