import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const url = new URL('./workspace-api.mjs', import.meta.url);
async function module() { assert.ok(fs.existsSync(url),'workspace API with native mapping and scoped search must exist'); return import(url); }
test('FDA datasets retain the exact selected collection identity',async()=>{
 const m=await module(); assert.equal(m.collectionInfo('agency_safety_openfda_device_pma').id,'agency_safety_openfda_device_pma');
 assert.notEqual(m.collectionInfo('agency_safety_openfda_device_pma').label,m.collectionInfo('agency_safety_openfda_drugsfda').label);
});
test('same id in different collections remains different',async()=>{const m=await module();assert.notEqual(m.recordKey('sources','1'),m.recordKey('court_documents','1'));});
test('matter filing rows display the filing rather than repeating the caption',async()=>{const m=await module();assert.equal(m.displayRecord('mdl_docket_documents',{id:'x',title:'IN RE: Big Matter',cells:{description:'Order setting trial',entry_date_filed:'2026-01-01'}}).title,'Order setting trial');});
test('recorded court end date overrides an inconsistent in-use flag',async()=>{const m=await module();const c=m.normalizeCourt({id:'old',state:'IL',title:'Historical',facts:[['Ended (CourtListener end_date)','1855-02-13'],['In use (CourtListener flag)','yes']]});assert.equal(c.historical,true);assert.equal(c.statusConflict,true);});
test('unknown court status is not manufactured as current',async()=>{const m=await module();const c=m.normalizeCourt({id:'x',facts:[]});assert.equal(c.status,'not_recorded');});
test('court state is explicit and never derived from a hostname',async()=>{const m=await module();const c=m.normalizeCourt({id:'cand',state:'',url:'https://www.ca.gov'});assert.equal(c.state,'');});
test('invalid and zero MDL selectors are rejected',async()=>{const m=await module();for(const x of ['0','-1','1 OR 1=1','abc'])assert.equal(m.validMdl(x),false);assert.equal(m.validMdl('3047'),true);});
test('unrecognized dataset never resolves to a broader collection',async()=>{const m=await module();assert.equal(m.collectionInfo('unexpected'),null);});
test('a held collection cannot be read through the new record endpoint',async()=>{const m=await module();let called=false;const r=await m.handleWorkspace('/api/workspace/record',{dataset:'court_documents',id:'x'},{dataset:async()=>({ready:false}),detail:async()=>{called=true;return {}}});assert.equal(r.status,503);assert.equal(called,false);});
test('unsupported query filters fail instead of disappearing',async()=>{const m=await module();const r=await m.handleWorkspace('/api/workspace/records',{dataset:'court_documents',invented:'x'},{dataset:async()=>({id:'court_documents',ready:true,metadata:{listing:{filters:[]}}})});assert.equal(r.status,400);});
test('text search receives exact dataset and court scopes',async()=>{const m=await module();let sent;const c={dataset:async()=>({id:'court_documents',ready:true,metadata:{listing:{filters:[{name:'court'}]}}}),rpc:async(n,p)=>{sent=p;return {items:[],has_more:false}},datasets:async()=>[{id:'court_documents',ready:true}]};await m.handleWorkspace('/api/workspace/records',{dataset:'court_documents',q:'evidence',court:'ilnd'},c);assert.deepEqual(sent.p_datasets,['court_documents']);assert.equal(sent.p_filters.court,'ilnd');});
test('global search only selects permitted published collections',async()=>{const m=await module();let sent;await m.handleWorkspace('/api/workspace/records',{q:'talc'},{datasets:async()=>[{id:'court_documents',ready:true},{id:'open_us_law',ready:false},{id:'coverage_labels',ready:true}],rpc:async(n,p)=>{sent=p;return {items:[],has_more:false}}});assert.deepEqual(sent.p_datasets,['court_documents']);});
test('reader returns exact cross-source entry relationships',async()=>{const m=await module();let sent;const r=await m.handleWorkspace('/api/workspace/record',{dataset:'mdl_docket_activity',id:'entry-12'},{dataset:async()=>({ready:true}),detail:async()=>({id:'entry-12',title:'Entry 12'}),rpc:async(n,p)=>{sent={n,p};return {items:[{dataset:'mdl_docket_documents',record_id:'doc-12',item:{title:'Caption',cells:{description:'Trial order'}}}],total:1,basis:'native id'}}});assert.equal(sent?.n,'corpus_workspace_entry_relations');assert.equal(sent?.p.p_dataset,'mdl_docket_activity');assert.equal(r.related.items[0].title,'Trial order');});
test('dates must not disappear from a user query',async()=>{const m=await module();const r=await m.handleWorkspace('/api/workspace/records',{dataset:'court_documents',dfrom:'2026-01-01'},{dataset:async()=>({id:'court_documents',ready:true,metadata:{listing:{filters:[{name:'dfrom'}]}}}),rpc:async()=>({items:[]})});assert.equal(r.status,400);});
